### ISSUE TITLE
No connection when rcon tool runs behind nginx proxy

### ISSUE THREAD

**Issue by heliax01** [cemathey/hll_seed_vip#3]
Problem is that nothing is listening on "website.com:443", but "https://website.com" is working fine. Behind Nginx proxy it would just be "website" subdomain name based. Is there a way to get rid of the additional ":443"?

```
hll_seed_vip-public-seed-tool  | 2024-02-07 07:45:04.885 | ERROR    | hll_seed_vip.io:wrapped:30 - all attempts to connect to website.com:443 failed
hll_seed_vip-public-seed-tool  | 2024-02-07 07:45:04.885 | WARNING  | hll_seed_vip.io:wrapped:31 - Retrying attempt 1, sleeping for 0 seconds for https://website.com/ function=get_gamestate
```

**Comment by heliax01** [comment]
https://website.com/ is what i have in the base_url field. Putting in `[https://website.com:443/](https://website.com/)" produces exactly the same error.

**Comment by heliax01** [comment]
I have had the same problem with setting up CRCON's stats page. The workaround was to setup an additional subdomain and pointing the proxy url to :7010, because the stats page uses a separate website.
This is not the case here, so I managed to get it working by setting up hll_seed_vip on the same proxied host and pointing the base_url to http://192.168.xxx.xxx:8010

Thanks for looking into this and all the work you do for the HLL community!

**Comment by cemathey** [comment]
> I have had the same problem with setting up CRCON's stats page. The workaround was to setup an additional subdomain and pointing the proxy url to :7010, because the stats page uses a separate website. This is not the case here, so I managed to get it working by setting up hll_seed_vip on the same proxied host and pointing the base_url to http://192.168.xxx.xxx:8010
> 
> Thanks for looking into this and all the work you do for the HLL community!

That is interesting because it's just making HTTP calls to the API, it shouldn't be any different than when you use CRCON through the browser.

Did you try matching the same URL you use when you access CRCON through a browser? I'm not familiar with nginx at all really or proxies, but I'm glad you found a fix.
